# Command to all profiles
app:
  version: "0.1"
  jwt:
    secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration: 86400000 # a day
    refresh-token:
      expiration: 604800000 # 7 days

spring:
  main:
    banner-mode: "off"
  web:
    resources:
      add-mappings: "false"
  mvc:
    throw-exception-if-no-handler-found: "true"

logging:
  # config: ./config/logback.xml
  pattern:
    file: "%d{dd-MM HH:mm} - %-5level - %logger{1} - %msg%n"
  file:
    name: logs/app.log
  level:
    root: WARN
    org:
      hibernate: error
      springframework: WARN
    com:
      mak: INFO
